name: project_thera_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_client: 3.2.0
  serverpod_auth_idp_client: 3.2.0
  serverpod_client: 3.2.0

