name: project_thera_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.2.0
  serverpod_auth_server: 3.2.0
  serverpod_auth_idp_server: 3.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.2.0
  test: ^1.25.5


serverpod:
  scripts:
    # Starts the server and applies migrations
    start: dart bin/main.dart --apply-migrations

    # Build the Flutter web app and move it to the server's web directory
    # 
    # Unfortunately, we can't use the `-o` flag directly because of an error
    # that happens on windows. Issue is tracked in the flutter
    # repository here: https://github.com/flutter/flutter/issues/157886
    flutter_build: cd ../project_thera && flutter build web --base-href /app/ --wasm && rm -rf ../project_thera_server/web/app && mv build/web/ ../project_thera_server/web/app
